# Site settings
title: "Curious Machines"
author: "Steven Schmatz"
description: "This is primarily a technical blog, focused on the fields of reinforcement learning, machine intelligence, mathematics, and art."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am Steven Schmatz, an incoming graduate student in the <a href='https://umich.edu'>University of Michigan</a>'s engineering school. I currently focus on research in deep reinforcement learning."
colophon: "Content available under the <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons</a> license unless otherwise noted.<br>"

baseurl: ""
url: "https://stevenschmatz.com"

twitter_username: stevenschmatz
github_username: stevenschmatz
linkedin_username: steven-schmatz
facebook_username: schmatzarella
google-analytics: UA-69060-5

simple_search: https://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
